"""test clean state

Revision ID: 19233fa97e26
Revises: 001
Create Date: 2026-03-06 15:25:23.935760

"""
from alembic import op
import sqlalchemy as sa

# alembic is a tool for managing database schema changes (migrations) in SQLAlchemy projects.
# Each migration script has an upgrade() function to apply changes and a downgrade() function to revert
# updates the strture of database safely when the models change. This file is auto-generated by alembic when you run `alembic revision --autogenerate -m "message"`.
# revision identifiers, used by Alembic.
revision = '19233fa97e26'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
